# Generated by Django 3.0 on 2019-12-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='corps',
            field=models.TextField(max_length=90000),
        ),
    ]
