# Generated by Django 3.0 on 2019-12-06 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20191206_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
